apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubeops-insight.fullname" . }}-backend
  labels:
    {{- include "kubeops-insight.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
---
{{- if .Values.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubeops-insight.fullname" . }}-frontend
  labels:
    {{- include "kubeops-insight.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
{{- end }}
